---
title: "ggplot practice"
author: "Rahul Kasar"
date: "10/3/2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(grid)
library(jpeg)
library(ggplot2)
library(RCurl)
```

```{r read in Data}
kobe=read.csv('kobe.csv')
```

```{r 0,1 shot type }
head(kobe)
kobe <- mutate(kobe, shot.type = ifelse(shot_type== '2PT Field Goal', 0,1))


#combined shot type 
unique(kobe$combined_shot_type)
kobe <- mutate(kobe, jumpshot = ifelse(combined_shot_type== 'Jump Shot', 1,0))
kobe <- mutate(kobe, Dunk = ifelse(combined_shot_type== 'Dunk', 1,0))
kobe <- mutate(kobe, Layup = ifelse(combined_shot_type== 'Layup', 1,0))
kobe <- mutate(kobe, Tip_Shot = ifelse(combined_shot_type== 'Tip Shot', 1,0))
kobe <- mutate(kobe, Hook_Shot = ifelse(combined_shot_type== 'Hook Shot', 1,0))
## if all zero shot type is bank shot


 #shot location
kobe <- mutate(kobe, Mid_Range = ifelse(shot_zone_basic== 'Mid-Range', 1,0))
kobe <- mutate(kobe, Restricted_area = ifelse(shot_zone_basic== 'Restricted Area', 1,0))
kobe <- mutate(kobe, In_paint = ifelse(shot_zone_basic== 'In The Paint (Non-RA)', 1,0))
kobe <- mutate(kobe,  Above_Break3 = ifelse(shot_zone_basic== 'Above the Break 3 ', 1,0))
kobe <- mutate(kobe,  Right_corner3 = ifelse(shot_zone_basic== 'Right Corner 3', 1,0))
kobe <- mutate(kobe,  Backcourt = ifelse(shot_zone_basic== 'Backcourt', 1,0))
## if all zeros then left corner 3. 

```




```{r, getting image of court}
courtImg.URL <- "https://thedatagame.files.wordpress.com/2016/03/nba_court.jpg"
court <- rasterGrob(readJPEG(getURLContent(courtImg.URL)),
           width=unit(1,"npc"), height=unit(1,"npc"))
#kobe$shot_made_flag <- as.factor(kobe$shot_made_flag)

```

```{r, plot on court}
# plot using NBA court background and colour by shot zone
ggplot(kobe, aes(x=loc_x, y=loc_y)) +
      annotation_custom(court, -250, 250, -50, 420) +
      geom_point(aes(colour = shot_zone_area, shape = shot_made_flag)) +
      xlim(-250, 250) +
      ylim(-50, 420)


```

```{r, remove NA}
kobe$one<- rep(1, nrow(kobe))
final.test <- kobe[is.na(kobe$shot_made_flag),]
kobe.2<- kobe[!is.na(kobe$shot_made_flag),]
kobe.2
```


```{r}
class(kobe.2$shot_made_flag)
#kobe.2$shot_made_flag <- as.numeric(kobe.2$shot_made_flag)

kobe.3 <- kobe.2[,c(15,18,38)]
#kobe.3$shot_made_flag <- as.factor(kobe.3$shot_made_flag)
shot.percent <- kobe.3 %>% group_by(shot_zone_basic) %>% summarise(made=sum(shot_made_flag), taken=sum(one))
shot.percent$percent <- shot.percent$made/shot.percent$taken
sp <- shot.percent
sp
```

```{r test}
sp
k2 <- kobe.2
k2

```

```{r}
class(kobe.2$shot_made_flag)
k2<- merge(x = k2, y = sp, by = "shot_zone_basic", all.x = TRUE)
k2

k2$shot_made_flag <- as.factor(k2$shot_made_flag)
ggplot(k2, aes(x=loc_x, y=loc_y, shape ='.')) +
      annotation_custom(court, -250, 250, -50, 420) +
      geom_point(aes(colour = percent, shape = shot_made_flag)) +
      xlim(-250, 250) +
      ylim(-50, 420)

```










