---
title: "Kobe"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
# Cleaning Data: creating clean dataframes
setwd("~/Documents/GitHub/Kobe")
library(dplyr)
kobe <- read.csv("Kobe.csv")

# removing NA values
#kobe.na includes all NA values for Shot Made
kobe.na <- kobe[is.na(kobe$shot_made_flag),]
#kobe.clean includes all values that are not NA
kobe.clean <- kobe[!is.na(kobe$shot_made_flag),]
kobe.clean$one <- rep(1)
```

``` {r}
# Creating Shot Percentages in various zones 

# shot.percent is new dataframe with shot percentage in each basic zone
shot.percent <- kobe.clean %>% 
  group_by(shot_zone_basic) %>%                            
  summarise(made = sum(shot_made_flag), taken = sum(one))
shot.percent$percent <- shot.percent$made/shot.percent$taken

# sp.detailed is a new dataframe with shot percentage in each zone area
sp.detailed <- kobe.clean %>% 
  group_by(shot_zone_area) %>%                            
  summarise(made = sum(shot_made_flag), taken = sum(one))
sp.detailed$percent <- sp.detailed$made/sp.detailed$taken

# heat is new dataframe with shot percentage at each distance in each zone
heat <- kobe.clean %>% 
  group_by(shot_zone_area, shot_zone_range) %>%                            
  summarise(made = sum(shot_made_flag), taken = sum(one))
heat$percent <-  heat$made/heat$taken
```

```{r}
# Shot percentage by zone and distance on a Court Map

library(dplyr)
library(grid)
library(jpeg)
library(ggplot2)
library(RCurl)

courtImg.URL <- "https://thedatagame.files.wordpress.com/2016/03/nba_court.jpg"
court <- rasterGrob(readJPEG(getURLContent(courtImg.URL)),
           width=unit(1,"npc"), height=unit(1,"npc"))

# Creating new datafram kobe.factor where shot_made_flag is a factor
kobe.clean$zone_and_range <- kobe.clean$shot_zone_area:kobe.clean$shot_zone_range

heat$zone_and_range <- heat$shot_zone_area:heat$shot_zone_range

kobe.factor <- kobe.clean
kobe.factor$shot_made_flag <- as.factor(kobe.factor$shot_made_flag)

# Creating New Dataframe map by merging kobe.factor and shot.percent
#map <- merge(x = kobe.factor, y = heat, by = percent, all.x = TRUE)
map.zone <- merge(x = kobe.factor, y = heat, by = "shot_zone_area", all.x = TRUE)
map.range <- merge (x = kobe.factor, y = heat, by = "shot_zone_range", all.x = TRUE)

map.zone.range <- merge (x = kobe.factor, y = heat, by = "zone_and_range", all.x = TRUE)
# Currently gives same percentage for entire area: want area and range

# plot using NBA court background and colour by shot zone
zonemap <- ggplot(kobe.factor, aes(x=loc_x, y=loc_y)) +
      annotation_custom(court, -250, 250, -50, 420) +
      geom_point(aes(colour = shot_zone_area, shape = shot_made_flag)) +
      xlim(-250, 250) +
      ylim(-50, 420)
# plot using NBA court background and colour by shot zone and distance
zone_map_distance <- ggplot(kobe.factor, aes(x=loc_x, y=loc_y)) +
      annotation_custom(court, -250, 250, -50, 420) +
      geom_point(aes(colour = shot_zone_area:shot_zone_range, shape = shot_made_flag)) +
      xlim(-250, 250) +
      ylim(-50, 420)
# plot using NBA court background and colour by zone and percentage
zone_percent <- ggplot(map.zone, aes(x=loc_x, y=loc_y)) +
      annotation_custom(court, -250, 250, -50, 420) +
      geom_point(aes(colour = percent, shape = shot_made_flag)) +
      xlim(-250, 250) +
      ylim(-50, 420) + scale_color_gradientn(colours = rainbow(8))
# plot using NBA court background and colour by zone, area and percentage
heatmap <- ggplot(map.zone.range, aes(x=loc_x, y=loc_y)) +
      annotation_custom(court, -250, 250, -50, 420) +
      geom_point(aes(colour = percent, shape = shot_made_flag)) +
      xlim(-250, 250) +
      ylim(-50, 420) +scale_color_gradientn(colours = rainbow(8))
zonemap
zone_map_distance
zone_percent
heatmap
```

